# Generated by Django 5.1.2 on 2024-11-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
    ]
